baseURL = 'https://areaconcept.eu.org/'
languageCode = 'en-us'
title = 'Area Concept School'
theme = 'ananke'

googleAnalytics = "G-749R9984YW"

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/Area_Concept"